name: Smoke test

on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.11
    - run: yarn install
    - run: yarn link eslint-plugin-knex
    - run: yarn test:smoke
      env:
        CI: true
